### ISSUE TITLE
Add in missing docs / sessions

### ISSUE THREAD

**Issue by ryanblock** [arc-repos/arc.codes#42]

**Comment by mikemaccana** [comment]
I notice the session example in the intro is a little outdated. I'm not sure if this is everything you want but I'll update that now.

**Comment by mikemaccana** [comment]
PS I mean the 'Example App' in https://arc.codes/guides/http uses old style session APIs - updating https://github.com/arc-repos/arc-example-login-flow first (since that's what it's quoting), then that.

**Comment by mikemaccana** [comment]
@ryanblock I've updated the tests to pass on arc 4 and also merged with current m,aster - this should be ready to go! 😃

**Comment by ryanblock** [comment]
Thanks for this! Much needed.

Couple quick bits: first, build is currently failing, some due to typos (both real and that need to be added to the dictionary file), and also linter, if you could take a look at that.

On our side, I've got a bit of coordinating with the JSF to do to see whether we need to re-deploy the DNS on this changeover. Please stand by!

**Comment by ryanblock** [comment]
One other thing – always prefer `git mv` to regular moves, which kills all version history for files. If you could move those back and just do a simple git mv (which I think should still be possible), that'd be much obliged!

**Comment by mikemaccana** [comment]
Thanks Ryan! Fixed the typos.

For the moves it looks like vscode didn't do a 'git mv' when I renamed the
dir (which is weird, since it's an editor and all). It's 1AM here and I'm
in bed so will do a git mv and resend tomorrow.

**Comment by ryanblock** [comment]
No worries, and much obliged!

**Comment by mikemaccana** [comment]
Done! https://github.com/arc-repos/arc.codes/pull/54

It looks like git doesn't like renames and file changes in the same commit, so I've split it into the renames, the arc4 arc.codes site upgrade, and the content changes, then merged in your changes.

**Comment by ryanblock** [comment]
Thanks, Mike! Pls peep files changed: https://github.com/arc-repos/arc.codes/pull/54/files for the list of files that are still showing up as having been deleted and recreated. Looks like you successfully got the packages moved, but unfortunately not the index.js files.

Also a bit of good news: did some research yesterday and I think we should be able to ship this  without further coordination from the foundation once this is all ready to merge. 🌈

**Comment by ryanblock** [comment]
Merged and deployed, thanks for this, Mike!

**Comment by mikemaccana** [comment]
Thanks Ryan! Super glad it was GitHub showing things oddly. 

We could export and test a `_pathToFileName` if you want to make sure we're aware of regressions. I know some people dislike testing private code though.
